source 'https://cdn.cocoapods.org'
platform :ios, '14.1'

target 'KlipperX' do
  use_frameworks!
  pod 'common', :path => '../common'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force CocoaPods targets to always build for x86_64
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'x86_64'
    end
  end
end