name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
jobs:
  build:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew package
      - name: Upload package
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: KlipperX-${{ matrix.os }}.zip
          path: ./**/build/compose/binaries/main

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./
      - name: Zip Artifacts
        run: |
          mkdir archived
          ls -d1 *.zip | xargs -I name sh -c "cd name; zip -r ../archived/name ./; cd .."
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: "./archived/*.zip"
          generate_release_notes: true
