name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
jobs:
  test:
    name: Run Desktop Unit Test
    strategy:
      matrix:
        platform: [linux, windows, macos, android]
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
          - platform: android
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Desktop Unit Test
        run: ./gradlew cleanDesktopTest desktopTest
        if: ${{ matrix.platform != 'android' }}
      - name: Android Unit Test
        run: ./gradlew cleanTestDebugUnitTest testDebugUnitTest
        if: ${{ matrix.platform == 'android' }}
      - name: Upload HTML reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.platform }}-reports.zip
          path: ./**/build/reports/tests
      - name: Upload XML Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }})-unit-test-results.zip
          path: ./**/build/test-results/**/*.xml

  publish-test-results:
    name: Publish Unit Tests Results
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/Test-.xml
